version: "3.9"
services:
  backend:
    healthcheck:
      test: curl --fail http://localhost/health || exit
      interval: 5s
      timeout: 2s
      retries: 5
    expose:
      - "80"
      - "443"