version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    healthcheck:
      test: pg_isready -U postgres -d postgres
      #test: psql -h localhost -U $POSTGRES_USER -c "select 1;" -d $POSTGRES_DB
      interval: 5s
      timeout: 2s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    